#!/bin/sh
# From http://samrowe.com/wordpress/ssh-agent-and-gnu-screen/:
# Attach to a tmux session, while forarding SSH agent.
SSHV="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for x in ${SSHV} ; do
    (eval echo $x=\$$x) | sed  -e 's/=/="/' -e 's/$/"/' -e 's/^/export /'
done 1>$HOME/scripts/fixssh && chmod +x $HOME/scripts/fixssh

tmux -2 new-session -A -s $1
