#!/bin/sh
# Brightness control, for internal and external monitors

# If you're not in the i2c group, fix that!
# And- try to set up modprobe to load i2c-dev on startup.

set -eux



brightnessctl "$@"

# Apply to external monitors too:
PERCENT="$(( $(brightnessctl get) * 100 / $(brightnessctl max) ))"
MAX="$(ddcutil getvcp 10 | grep -o 'max .*' | grep -o '[0-9]*')"
NEW="$(( MAX * PERCENT / 100 ))"
ddcutil setvcp 10 "$NEW"

