#!/bin/sh -ex

GOFILES="$(find . -name '*.go' | tr '\n' ' ')"
RUSTFILES="$(find . -name '*.rs' | tr '\n' ' ')"

if test -n "$GOFILES"
then
  gofmt -w -s $GOFILES
fi

if test -n "$RUSTFILES"
then
  rustfmt $RUSTFILES
fi
