#!/bin/sh

# Install and/or invoke Komanda

if ! which komanda-cli >/dev/null 2>&1
then
  echo "Installing Komanda"
  go get github.com/mephux/komanda-cli \
    && go install github.com/mephux/komanda-cli \
    || {
    echo 2>&1 "Error installing komanda-cli"
    exit 1
  }
fi

CFG="$HOME/secrets/komanda.cfg"
WORKCFG="$HOME/work.komanda.cfg"
if test -f "$WORKCFG"
then
  CFG="$WORKCFG"
fi

exec komanda-cli -c $CFG
