#!/bin/sh
if pgrep csd-screensaver >/dev/null || pgrep -f cinnamon-screensaver >/dev/null
then
  echo 'cinnamon locking'
  cinnamon-screensaver-command --lock
elif pgrep gnome-screensaver >/dev/null
then
  echo 'gnome locking'
  gnome-screensaver-command --lock
elif pgrep xscreensaver >/dev/null
then
  pgrep xscreensaver
  xscreensaver-command --lock
else
  echo "Don't know how to lock!" 1>&2
fi
