#!/usr/bin/env bash
# Lock, and in the background, fetch a new image from Imgur for the next lock.

LID=$HOME/.lockimg

INIT_IMG="CmvNKNT"
INIT_ALBUM="26GWw"

getimg() {
  link=$1
  curl -so /tmp/convfile $link 
  convert /tmp/convfile $LID/lockfile.png 2>/dev/null && rm /tmp/convfile
  # TODO Use symlinks here for atomic move.
}

# First-run setup...
mkdir -p $LID
if [ ! -e $LID/lastdata ] || [ ! -e $LID/next ]
then

  cat - <<HRD > ${LID}/lastdata
{
  "album": "$INIT_ALBUM",
  "img": "$INIT_IMG",
  "link": "https://i.imgur.com/$INIT_IMG.jpg"
}
HRD

  echo "$LID/$INIT_IMG.png" > $LID/next
fi
if [ ! -e $LID/lockfile.png ]
then
  getimg https://i.imgur.com/$INIT_IMG.jpg
fi

# On each run...
## Grab the image to use
## Run the updater in the background
(getimg $(lockscrn_rotate.py) ) &

## Lock, and delete the most recent image when done, if there's a newer one.
(
  i3lock --image $LID/lockfile.png 2>/dev/null \
    || i3lock --color 00000 2>/dev/null
)
 # Fall back to locking without an image; better to lock unprettily than fail to lock.
