#!/bin/sh
if which gnome-screensaver-command >/dev/null
then
  echo 'gnome locking'
  gnome-screensaver-command --lock
elif pgrep xscreensaver >/dev/null
then
  pgrep xscreensaver
  xscreensaver-command --lock
else
  echo "Don't know how to lock!" 1>&2
fi
