#!/bin/sh

# Meta-menu: menu of menus

MENU="$(
  find -L ~/scripts -regex '.*-menu' \
| xargs -n1 basename \
| cut -d'-' -f1 \
| sort \
| ~/scripts/menuize "Menu: ")"

test -n "$MENU" || exit 1

exec ~/scripts/"$MENU"-menu
