#!/bin/sh

# dmenu/bemenu wrapper: "menuize" a list, making the first items easy to reach.
# Argument 1 is the prompt to use; items are passed through via stdin.

# INDEX=1

column -t \
| ~/scripts/somemenu -l 20 -p "$1" \
| sed 's/^[0-9]\+ \+//'

