#!/bin/bash

# Initializes a new project using geosoft's
# master-makefile system, tracked with git.

GEOSOFT=~/dev/cceutils/scripts/no/geosoft/development/javamake/

# Make directory for project...
PROJECT_NAME="$1"
mkdir $PROJECT_NAME
cd $PROJECT_NAME

# make subdirectories
mkdir src
mkdir src/com
mkdir src/com/cceckman
mkdir src/com/cceckman/$PROJECT_NAME

mkdir obj
mkdir bin
mkdir make
mkdir docs

CODEBASE="c"
# Copy project makefile, modify with project name
if [ `echo $2 | tr [:upper:] [:lower:]` = `echo java | tr [:upper:] [:lower:]` ]
then CODEBASE="java"
fi

if [ "${CODEBASE}" = "java" ] 
then
PROJMKF="${GEOSOFT}/java_project_makefile"
else
PROJMKF="${GEOSOFT}/project_makefile"
fi

cp ${PROJMKF} ./dep_makefile

WD=`pwd`

cat "${GEOSOFT}/project_makefile_gen.sh" | \
    sed "s/__geosoft__/${GEOSOFT}/g" | sed "s/__devroot__/${WD}/g" | sed "s/__codebase__/${CODEBASE}/g" \
    > ./make/project_makefile_gen.sh

./make/project_makefile_gen.sh
