#!/bin/sh

ACTION="$(cat <<EOF | ~/scripts/menuize "Terminate: "
lock
restart
sway-exit
poweroff
EOF
)"

case "$ACTION" in
  lock)
    swaylock -f -c 000000
    ;;
  sway-exit)
    swaymsg exit
    ;;
  restart)
    systemctl reboot
    ;;
  poweroff)
    systemctl poweroff
    ;;
esac

