#!/bin/sh

ACTION="$(cat <<EOF | ~/scripts/menuize "Terminate: "
lock
sleep
logout
restart
off
EOF
)"

case "$ACTION" in
  lock)
    swaylock -f -c 000000
    ;;
  sleep)
    systemctl suspend
    ;;
  logout)
    swaymsg exit
    ;;
  restart)
    systemctl reboot
    ;;
  off|poweroff)
    systemctl poweroff
    ;;

esac

