#!/bin/sh

ACTION="$(cat <<EOF | ~/scripts/menuize "Terminate: "
lock
suspend
sway-exit
restart
off
EOF
)"

case "$ACTION" in
  lock)
    swaylock -f -c 000000
    ;;
  sleep)
    systemctl suspend
    ;;
  logout)
    swaymsg exit
    ;;
  restart)
    systemctl reboot
    ;;
  off|poweroff)
    systemctl poweroff
    ;;

esac

