#!/bin/sh

if ! test -f ~/.config/home-assistant/token
then
  swaynag -t warning -m "No Home Assistant token available! See $(realpath $0)"
  exit 1
fi

if ! test "$#" -eq 1
then
  exit 1
fi

hass_post() {
  ENDPOINT="$1"
  curl -s \
    -H "Authorization: Bearer $(cat ~/.config/home-assistant/token)" \
    -H "Content-Type: application/json" \
    http://homeassistant.monkey-heptatonic.ts.net:8123/"$ENDPOINT" \
    -d @-
}


cat <<EOS | hass_post api/services/scene/turn_on
{
    "entity_id": "${1}"
}
EOS
