#!/bin/bash

# This script accepts as a single argument a web site (think and index.html),
# downloads all linked pages, and concatenates them into a single .html file with
# embedded anchor links.

# It then calls Amazon's KindleGen program (https://kdp.amazon.com/self-publishing/help?topicId=A3IWA2TQYMZ5J6)
# and creates the file book.mobi, which is Kindle-compatible.

# The test case was http://glprogramming.com/red/, which it seems to have
# mostly worked with.


# make temp directory
mkdir site
cd site

# get index page
wget -q -O index.html $1 
# Whoops! What if there are no newlines anywhere because the author of the site is a horrible horrible person?
cat index.html | sed 's/</\
&/g' | sed -n "s/.*[hH][rR][eE][fF]=\"\([^.]*\.html\)\".*/\1/p" > index.list

# Extract link listing

# download provided site's pages
wget -pkq -nc -nd -B $1 -i index.list

# Done downloading

# Concatenate into book.html, replacing links with anchor tags
cat index.html | sed -e "s/<\/[hH][tT][mM][lL]>//g" -e "s/<\/[Bb][Oo][dD][Yy]>//g" \
    -e "s/\(.*[hH][rR][eE][fF]=\"\)\([^.]*\)\.html\(\".*\)/\1#\2\3/" \
    -e "s/<[bB][oO][dD][yY]>/<body><a name=\"index.html\">/" \
> book.html

while read LINE; do
FNAME=`echo ${LINE} | sed -E -e "s/(.*)\.html/\1/"`
echo "<a name=\"${FNAME}\" />" >> book.html
cat ${LINE} | sed -E \
    -e "s/<[\/]?[hH][tT][mM][lL]>//g" \
    -e "s/<[\/]?[Bb][Oo][dD][Yy]>//g" \
    -e "s/.*(<[aA][ ]*[nN][aA][mM][eE])[ ]*=[ ]*[\"]?([^\">]*)[\"]?([^\/>]*)[\/]?>(.*)/\1=\"${FNAME}-\2\"\3\/>\4/" \
    -e "s/(.*[hH][rR][eE][fF]=\")([^#]*)#([^\"]*)\"(.*)/\1\2-\3\"\4/" \
    -e "s/(.*[hH][rR][eE][fF]=\")([^.]*)\.html([^\"]*)\"(.*)/\1#\2\3\"\4/" \
    >> book.html
done < index.list
echo "</body></html>" >> book.html

kindlegen book.html

cp book.mobi ..
cd ..
#rm -rf site
