#!/bin/sh
# syscolor: figure out what bash prompt / screen color
# to use for this machine.

case "$(hostname | sha256sum | awk '{print $1}')" in
  212baeb*|f0295eb6f*|f074ac1a*)
    echo 'cyan'
    ;;
  dcd3aa9*|1b3f81796*|f40ed2a7f*)
    echo 'green'
    ;;
  1334c13*|021a2476d*|bfa820ad3*)
    echo 'magenta'
    ;;
  f5004d7*|80c1bf5da*|f5f3ee24e*)
    echo 'blue'
    ;;
  7b7b323*|2f1d3d82b*|aebeec14a*)
    echo 'yellow'
    ;;
  *)
    echo 'red';
    ;;
esac

