#!/bin/sh

if test -e ~/rcfiles/path.sh
then
  . ~/rcfiles/path.sh
fi

if command -v footclient >/dev/null
then
  exec footclient --server "$XDG_RUNTIME_DIR"/foot-server.sock "$@"
fi

if command -v alacritty >/dev/null
then
  exec alacritty "$@"
fi

if command -v konsole >/dev/null
then
  exec konsole "$@"
fi

exec xterm "$@"
