#!/bin/sh

if test -e ~/rcfiles/path.sh
then
  . ~/rcfiles/path.sh
fi

if command -v footclient >/dev/null
then
  # Robust starting of footclient:
  test -S "$XDG_RUNTIME_DIR"/foot-server.sock && {
     exec footclient --server "$XDG_RUNTIME_DIR"/foot-server.sock "$@"
  }
  systemctl --user restart foot-server
  sleep 0.2
  exec footclient --server "$XDG_RUNTIME_DIR"/foot-server.sock "$@"
fi

if command -v alacritty >/dev/null
then
  exec alacritty "$@"
fi

if command -v konsole >/dev/null
then
  exec konsole "$@"
fi

exec xterm "$@"
