#!/bin/sh

# Reconfigure the current theme, where we can.
exec 2>&1
exec 1>/tmp/log

THEME="$(echo "light\ndark" | ~/scripts/menuize 'Mode: ')"
test -n "$THEME" || exit 1

~/scripts/retheme "selenized" "$THEME"

