#!/bin/bash

repos=$(cat <<EOF
cceckman/cce3
cceckman/cceckman.github.io
cceckman/distro
cceckman/doit
cceckman/web
ccontavalli/ssh-ident
EOF
)

# Clone repositories I like / own.
GH_PREFIX="$HOME/r"
GO_PREFIX="$HOME/go" # Keep in sync with Tilde/.bashrc
mkdir -p $GH_PREFIX
mkdir -p $GO_PREFIX

ret=0

for repo in $repos
do
  REPOPATH="${GH_PREFIX}/${repo}"
  if ! [ -d "$REPOPATH" ]
  then
    # Not already cloned. Pull it down.
    {
      git clone "git@github.com:${repo}" "$REPOPATH" && \
        git submodule init
    } || {
      echo "Error cloning ${repo}, dropping to shell." \
        "Resolve any issues yourself."
      bash -i
    }
    ret=$(($ret + $?))
  fi
done

# Separately, update all of the repositories under $HOME/r, and $HOME itself.
# Do this so that the default list of repositories need not be "all of them".
for path in $(ls -d ${GH_PREFIX}/*/*) $HOME
do
  # If it's not cloned, attempt to sync it.
  pushd $path
  {
    git pull && git submodule update --recursive
  } || {
    echo "error updating $path, dropping to shell." \
     "Resolve any sync issues yourself."
    bash -i
  }

  # Maintain gopath.
  # Support Go directory structure. Assume $HOME/go is in $GOPATH.
  # Get back the 'repo' part of the name...
  repo=$(echo ${path#${GH_PREFIX}})
  # Early-exit for $HOME
  if [ $repo = "" ]; then popd; continue; fi
  
  GOTOOLPATH="$GO_PREFIX/src/github.com/${repo}"
  if ! [ "$GOTOOLPATH" -ef "$path" ]
  then
    mkdir -p $(dirname $GOTOOLPATH) && ln -s $path $GOTOOLPATH
  fi

  popd
done

# Link for ssh-ident.
# Suppress the hek out of errors.
ln -s $GH_PREFIX/ccontavalli/ssh-ident/ssh-ident $HOME/scripts/sshi \
  >/dev/null 2>&1 || true
