#!/bin/sh

GH_PREFIX="$HOME/r"
GO_PREFIX="$HOME/go/src" # Keep in sync with Tilde/.bashrc

ret=0


# Clone any new repositories.
if test "$#" -gt 0
then
  for repo in $@
  do
    REPOPATH="${GO_PREFIX}/github.com/${repo}"
    LNPATH="${GH_PREFIX}/${repo}"
    if ! [ -d "$REPOPATH" ]
    then
      # Not already cloned. Pull it down, and link r/.
      {
        mkdir -p "$REPOPATH"
        git clone "git@github.com:${repo}" "$REPOPATH" && \
          git submodule init && \
          mkdir -p "$LNPATH" && \
          rmdir "$LNPATH" && \
          ln -s "$REPOPATH" "$LNPATH"
      } || {
        echo "Error cloning ${repo}, dropping to shell." \
          "Resolve any issues yourself."
        $(getent passwd $USER | cut -d: -f7) -i
      }
      ret=$(($ret + $?))
    fi
  done
  exit
fi


# Separately, update all of the repositories under $HOME/r, and $HOME itself.
# Do this so that the default list of repositories need not be "all of them".
for path in $(ls -d ${GH_PREFIX}/*/*) $HOME
do
  # If it's not cloned, attempt to sync it.
  WD="$(pwd)"
  cd $path
  {
    git pull && git submodule update --init --recursive
  } || {
    echo "error updating $path, dropping to shell." \
     "Resolve any sync issues yourself."
    $(getent passwd $USER | cut -d: -f7) -i
  }

  cd "$WD"
done

# Link for ssh-ident.
# Suppress the hek out of errors.
ln -s $GO_PREFIX/src/github.com/ccontavalli/ssh-ident/ssh-ident $HOME/scripts/sshi \
  >/dev/null 2>&1 || true
