#!/bin/sh

set -eux

TEMPFILE="$(mktemp)"
# I've reviewed this and found it acceptable:
curl -Lo "$TEMPFILE" \
  https://raw.githubusercontent.com/sonowz/vscode-remote-wsl-nixos/7a7d380042a4d86bc98149b9273fdb14e0edfe74/flake/server-env-setup
chmod +x "$TEMPFILE"
exec "$TEMPFILE"
